name: deploy na AWS

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
    paths-ignore:
      - '*.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
       
    steps:
      - name: checkout 
        uses: actions/checkout@v4
           
      - name: configurar credenciais na AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Empacotar codigo lambda para zip
        run: |
          cd lambda && zip -r ../lambda.zip lambda_function.py bedrock.py

      - name: Deploy no Lambda
        run: |
            aws lambda update-function-code \
            --function-name voiceops-pipeline \
            --zip-file fileb://lambda.zip



